name: main

on:
  schedule:
    - cron: '0 23 * * 0,1,2,3,4'
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - run: pip install -r requirements.txt
      - run: python kenon.py
        env:
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}} 
